export enum ExercisesActionTypes {
    SET_EXERCISES = "SET_EXERCISES",
    ADD_EXERCISE = "ADD_EXERCISE",
    EDIT_EXERCISE = "EDIT_EXERCISE",
    DELETE_EXERCISE = "DELETE_EXERCISE",
    DELETE_BY_DAY = "DELETE_BY_DAY",
    DELETE_BY_PROGRAM = "DELETE_BY_PROGRAM"
}